default:
	@echo targets: server, bed-tbi-broad, bed-tbi-trena, bed-tbi-trena-tiny

server:
	python3 -m http.server 8001 &

bed-tbi-broad:
	open http://localhost:8001/bed-tbi-broad.html

bed-tbi-trena:
	open http://localhost:8001/bed-tbi-trena.html

bed-tbi-trena-tiny:
	open http://localhost:8001/bed-tbi-trena-tiny.html


